logging:
  level:
    root: info
spring:
  application:
    name: test
# Redis数据库索引（默认为0）
  redis:
    database: 0
  # Redis服务器地址
    host: 106.13.71.149
  # Redis服务器连接端口
    port: 6789
  # Redis服务器连接密码（默认为空）
    #password: "@lijunyoucan541288..|"
    password: "@lijunyoucan54188..|"
  # 连接超时时间（毫秒）
    timeout: 300
  datasource:
    url: jdbc:mysql://106.13.133.59:3306/Test
    username: root
    password: lijunyoucan54188..
    driver-class-name: com.alibaba.druid.proxy.DruidDriver